---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
# library(signal)
library(plotly)
library(patchwork)
```

```{r}
source('process_midlines.R')
```

```{r}
datadir <- '/Users/etytel01/Box/Katz lamprey kinematics/2021/Processed Data'
scalefile <- '/Users/etytel01/Box/Katz lamprey kinematics/2021/Processed Data/scales.csv'
```

```{r}
testfile = '/Users/etytel01/Box/Katz lamprey kinematics/2021/Processed Data/Exp_062921/Exp_062921/Animal1/2dpi/063021_A1V08_04DLC_resnet50_LesionsOct13shuffle1_1030000.csv'
```

```{r}
treatments = c("Control", "2hpi", "1dpi", "2dpi", "3dpi")
```

```{r}
fps = 60
```

```{r}
widthdata <- read_csv('/Users/etytel01/Box/Katz lamprey kinematics/2021/fishwidth.csv')
```

```{r}
scales <- read_csv(scalefile, col_types = list(Date = col_date("%m/%d/%y"),
                                               Animal = col_character(),
                                               Treatment = col_factor(levels = treatments)))
scales
```

```{r}
process_filepath <- function(filepath) {
  df <- str_match(filepath, 'Animal(\\d)/(Control|\\d[dh]pi)/(\\d{6})')
  colnames(df) <- c("all", "Animal", "Treatment", "Date")
  df %>%
    as_tibble() %>%
    mutate(Date = lubridate::mdy(Date),
           Treatment = factor(Treatment, levels = treatments)) %>%
    select(-all)
}
```

```{r}
process_filepath(testfile)
```

```{r}
data1 <- read_csv(testfile)
```
```{r}
bodypartorder = c("snout", "gill", "mid1", "mid2", "anus", "mid4", "tailbase", "tailtip")
```

```{r}
data1 <-
  bind_cols(data1, process_filepath(testfile)) %>%
  left_join(scales, by = c('Animal', 'Treatment', 'Date')) %>%
  mutate(t = frame / fps,
         xmm = x * Scale,
         ymm = y * Scale,
         bodyparts = factor(bodyparts, levels = bodypartorder),
         bodypartord = as.numeric(bodyparts))

```

```{r}
data1 %>%
  filter(frame >= 10 & frame <= 20) %>%
  group_by(frame) %>%
  plot_ly(x = ~xmm, y = ~ymm, type = "scatter", mode = "lines")
```

```{r}
data1 <- get_arc_length(data1)
len1 <- get_length(data1)
```

```{r}
data1 <- interpolate_width(data1, widthdata = widthdata$ammowidth)
data1
```

```{r}
data1 <-
  get_center_of_mass(data1)

data1 %>%
  filter(frame >= 10 & frame <= 20) %>%
  group_by(frame) %>%
  plot_ly(x = ~xmm, y = ~ymm, type = "scatter", mode = "lines") %>%
  add_markers(x = ~comx, y = ~comy)
```

```{r}
data1 <-
  get_swim_vel_dir(data1, fps = fps)
```

```{r}
data1 <-
  data1 %>%
  get_excursions()
```


```{r}
data1 %>%
  filter(bodyparts %in% c("snout", "tailtip")) %>%
  group_by(bodyparts) %>%
  plot_ly(x = ~t, y = ~exc, color = ~bodyparts, type = "scatter", mode = "lines")
  
```

```{r}
data1 <- 
  data1 %>% get_cycles()
```

```{r}
data1
```

```{r}
data1 %>%
  filter(bodyparts %in% c("tailtip", "anus", "snout")) %>%
  group_by(bodyparts) %>%
  plot_ly(x = ~phase, y = ~exc, color = ~bodyparts, type ="scatter", mode = "lines") %>%
  add_lines(y = ~cycle)
```

```{r}
data1 %>%
  get_amplitudes() %>%
  group_by(bodypartord, cycle) %>%
  summarize(amp = first(na.omit(amp)),
            t = first(t)) %>%
  summarize(amp = mean(amp, na.rm = TRUE)) %>%
  ungroup() %>%
  plot_ly(x = ~bodypartord, y = ~amp, type = "scatter", mode = "lines+markers")
```

```{r}
data1 %>%
  get_wavespeed() %>%
  group_by(bodyparts, bodypartord) %>%
  summarize(wavespeed = mean(wavespeed, na.rm = TRUE)) %>%
  ungroup() %>%
  plot_ly(x = ~bodypartord, y = ~wavespeed, type = "scatter", mode = "lines+markers")
```

```{r}
data1 %>%
  get_wavelength() %>%
  group_by(bodyparts, bodypartord) %>%
  summarize(wavelength = mean(wavelength, na.rm = TRUE)) %>%
  ungroup() %>%
  plot_ly(x = ~bodyparts, y = ~wavelength, type = "scatter", mode = "lines+markers")
  
```

```{r}
data1 %>%
  filter(zerocross != 0) %>%
  arrange(bodyparts)
```

```{r}
phbody <-
  data1 %>%
    ungroup() %>%
    filter(zerocross != 0 &
             bodyparts != "tailtip") %>%
    group_by(bodyparts) %>%
    mutate(dt = lead(t0) - t0,
           dfr = lead(frame) - frame,
           phstep = 0.5/dfr) %>%
  select(bodyparts, frame, phstep)


q <- data1 %>%
  left_join(phbody, by = c("bodyparts", "frame")) %>%
  group_by(bodyparts) %>%
  fill(phstep, .direction = "down") %>%
  mutate(phstep = if_else(is.na(phstep), 0, phstep),
    bodyphase = cumsum(phstep)) %>%
  arrange(bodyparts, frame)
```

```{r}
get_next_level <- function(fct) {
  lev <- levels(fct)
  n = as.numeric(fct) + 1
  
  good = (n >= 1) & (n <= length(lev))
  n[!good] = 1
  
  nextfct <- factor(lev[n], levels = lev)
  nextfct[!good] = NA
  nextfct
}
```


```{r}
data1 %>%
  get_wavespeed()
```
```{r}
testfile2 = '/Users/etytel01/Box/Katz lamprey kinematics/2021/Processed Data/Exp_062921/Exp_062921/Animal1/2hpi/062921_A1V14_04DLC_resnet50_LesionsOct13shuffle1_1030000.csv'
```

```{r}
load_katz_data <- function(filename, widthdata, fps, bodypartorder) {
  read_csv(filename) %>%
    bind_cols(process_filepath(filename)) %>%
    left_join(scales, by = c('Animal', 'Treatment', 'Date')) %>%
    mutate(t = frame / fps,
           xmm = x * Scale,
           ymm = y * Scale,
           bodyparts = factor(bodyparts, levels = bodypartorder),
           bodypartord = as.numeric(bodyparts)) %>%
    get_all_kinematics(widthdata = widthdata, fps = fps)
}
```

```{r}
data2 <-
  load_katz_data(testfile2, 
                 widthdata = widthdata$ammowidth, fps = fps,
                 bodypartorder = bodypartorder)
```

```{r}
p1 <- ggplot(data2, aes(x = t, y = swimvel)) +
  geom_line()

p2 <- 
  data2[seq(1,nrow(data2),30),] %>%
  ggplot(aes(x = t, y = 1, angle = atan2(swimdiry, swimdirx), radius = 0.05)) +
  geom_spoke() +
  coord_fixed()

p3 <-
  data2 %>%
  group_by(frame,t) %>%
  summarize(wavespeed = mean(wavespeed, na.rm = TRUE)) %>%
  ggplot(aes(x = t, y = wavespeed)) +
  geom_point()

p4 <-
  data2 %>%
  group_by(frame,t) %>%
  summarize(wavelength = last(na.omit(wavelength))) %>%
  ggplot(aes(x = t, y = wavelength)) +
  geom_point()

p5 <-
  data2 %>%
  group_by(bodyparts, bodypartord) %>%
  summarize(amp = mean(amp, na.rm = TRUE),
            s = mean(s, na.rm = TRUE)) %>%
  ggplot(aes(x = s, y = amp)) +
  geom_line()
  #geom_point(aes(color = bodyparts))

p6 <-
  data2 %>%
  group_by(bodyparts, bodypartord) %>%
  summarize(wavelength = mean(wavelength, na.rm = TRUE),
            s = mean(s, na.rm = TRUE)) %>%
  ggplot(aes(x = s, y = wavelength)) +
  geom_line()
  #geom_point(aes(color = bodyparts))

p1 + p3 + p4 + p5 + p6
```

